spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/proflow?TimeZone=UTC
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: mongodb://localhost:27017/proflow

server:
  port: 8080